aliases:
  - &filter-only-main
    branches:
      only:
        - main

version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm run check-format
      - run: npm run build

  deploy-website:
    docker:
      - image: circleci/node:14.5.0

    steps:
      - add_ssh_keys:
          fingerprints:
            # repo-specific deploy key
            - "3a:4a:09:a1:7e:64:aa:13:cc:31:3e:c9:51:46:c7:ed"
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "ops@darklang.com"
            git config --global user.name "Dark Ops"
            npm install --frozen-lockfile && GIT_USER=none USE_SSH=true CUSTOM_COMMIT_MESSAGE="[skip ci] Automated Deploy of $CIRCLE_SHA1 via CircleCI" npm run-script deploy

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
  build_and_deploy:
    jobs:
      - deploy-website:
          # Only run on direct commits to main
          filters: *filter-only-main
