aliases:
  - &filter-only-main

version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm run check-format
      - run: npm run build

  deploy-website:
    docker:
      - image: cimg/node:16.11.1

    steps:
      - add_ssh_keys:
          fingerprints:
            # repo-specific deploy key
            - "6f:c2:ae:f9:8e:45:e9:17:82:ea:d0:8b:66:93:11:88"
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "ops@darklang.com"
            git config --global user.name "Dark Ops"
            npm install --frozen-lockfile && GIT_USER=none USE_SSH=true CUSTOM_COMMIT_MESSAGE="[skip ci] Automated Deploy of $CIRCLE_SHA1 via CircleCI" npm run-script deploy

workflows:
  version: 2
  build:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - gh-pages
                - main

  build_and_deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
      - deploy-website:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
