aliases:
 - &filter-only-main
   branches:
     only:
       - main

version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.10.0
    steps:
      - checkout
      - run: |
          cd website
          npm ci
          npm run lint
          npm run check-format
          npm run build

  deploy-website:
    docker:
      - image: circleci/node:12.10.0

    steps:
      - add_ssh_keys:
          fingerprints:
            # repo-specific deploy key
            - "3a:4a:09:a1:7e:64:aa:13:cc:31:3e:c9:51:46:c7:ed"
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "ops@darklang.com"
            git config --global user.name "Dark Ops"
            cd website && npm install --frozen-lockfile && USE_SSH=true CUSTOM_COMMIT_MESSAGE="[skip ci] Automated Deploy of $CIRCLE_SHA1 via CircleCI" npm run publish-gh-pages

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
  build_and_deploy:
    jobs:
      - deploy-website:
         # Only run on direct commits to main
         filters: *filter-only-main
